In [1]:
a = [1,2,3,4,5,6]

In [2]:
import numpy as np

In [3]:
n_a = np.array(a)

In [4]:
n_a

array([1, 2, 3, 4, 5, 6])

In [5]:
n_a[0]

1

In [6]:
n_a[1]

2

In [7]:
last_index = len(n_a) - 1

In [8]:
n_a[last_index]

6

In [9]:
n_a[-1]

6

In [10]:
n_a[-2]

5

In [11]:
n_a[0:3]

array([1, 2, 3])

In [12]:
n_a[3:6]

array([4, 5, 6])

In [13]:
n_a[2:4]

array([3, 4])

In [14]:
n_a[1:6]

array([2, 3, 4, 5, 6])

In [15]:
n_a[0:0:6]

array([], dtype=int32)

In [ ]:
n_a[]